fixed: capitalised all input fields
chpr-tbrl/CHPRIS-FE pull request #24
Opened 2022-07-25 07:27 UTC by steph237

2022-07-25 10:11 UTC, nSedrickm requested changes
Great progress here! left some comments to help improve

I noticed only the TextFields were referenced for capitalization. What of the radios and checkbox input fields? Their values were to be capitalized aswell. Will these be handled here or in another PR?

2022-07-25 10:11 UTC, nSedrickm commented on src/pages/lab-results.js
> +
Same here, as mentioned for the follow ups page this code is better run in a useEffect hook

The text inputs on this page are not capitalized aswell

2022-07-25 10:11 UTC, nSedrickm commented on src/pages/new-record.js
> +
Text inputs are capitalized on typing. Well done!

However, it only works when the page is first visited. Creating a second record does not have the intented result.

Perhaps the useEffect hook could fix that

2022-07-25 10:11 UTC, nSedrickm commented on src/pages/specimen-collection.js
> +
As per the other comments. Some updates  here aswell

2022-07-26 05:32 UTC, steph237 commented
> Great progress here! left some comments to help improve
> 
> I noticed only the TextFields were referenced for capitalization. What of the radios and checkbox input fields? Their values were to be capitalized aswell. Will these be handled here or in another PR?

Yes as of now only the text fields are capitalized. Still figuring out if the radio buttons will be capitalized on clicked or if all the options will be capitalised

2022-07-26 10:50 UTC, closed without merging