update: Capitalize input fields
chpr-tbrl/CHPRIS-FE pull request #25
Opened 2022-07-26 11:01 UTC by steph237

2022-07-26 12:11 UTC, nSedrickm requested changes
Great progress here.  Capitalization works well mostly when creating but breaks the update mechanism of these pages. This is mostly because the code has been added in blocks that control the updating flow. I have left a few comments to help resolve this behavior.

Also look into using [amended commits ](https://www.atlassian.com/git/tutorials/rewriting-history). Reason being there is no need to keep adding commits for basically the same changes.

When you make new changes you can run ```git commit --amend``` this will override the old changes and open a window for you to update the commit message. You can just save at this point then push with a ```git push -f```. This will make sure only one commit exists in the pr at any point in time which makes the changes easier to update and review

Capitalizing the text fields could also be achieved with a [css text-transform](https://www.w3schools.com/cssref/pr_text_text-transform.asp)

2022-07-26 12:13 UTC, steph237 commented on src/pages/follow-up.js
> +  });
This is in the useEffect hook

2022-07-26 15:23 UTC, nSedrickm requested changes
This is looking quite promising. Everything is in place aside for some duplicate code. Left some comments to help improve

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/follow-up.js
> +    );
I think this code is unneccessary since we now have it in a seperate useEffect directly below

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/follow-up.js
> +
Nice one, works as expected

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/lab-results.js
> +
Same here, good work

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/outcome-recorded.js
> +
Works for Textfields. But not the text area

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/specimen-collection.js
> +
Please format your code with prettier before pushing. This space is unnecessary

2022-07-26 15:23 UTC, nSedrickm commented on src/pages/update-record.js
> +      }
Since now have the code in a useEffect below, how about removing this one here as it is no longer needed

2022-07-26 15:29 UTC, nSedrickm commented on src/pages/lab-results.js
> +
Any reason for this?

2022-07-26 15:29 UTC, nSedrickm commented on src/pages/lab-results.js
> +                  <RadioButton labelText="No AFB seen" value="no_afb_seen" style={{ color: "red" }}/>
Please update. There is no need for expicitly styling this input

2022-07-28 10:44 UTC, nSedrickm requested changes
Looking good @stephanie nkwatoh All texfields and textareas are capitalized.

You accidentally updated a label on the new records page. Please update 

Once done, update your working branch with the recent changes from dev 

```git pull origin dev -r```

And we will be able to merge

2022-07-28 10:44 UTC, nSedrickm commented on src/pages/new-record.js
> +              <RadioButton labelText="Female1" value="female" id="female" />
You must have missed this one. All you need do is remove the 1 after Female

2022-07-28 13:04 UTC, nSedrickm approved these changes

2022-07-28 13:05 UTC, merged